### ISSUE TITLE
Syntax error on postgresql backslash command

### ISSUE THREAD

**Issue by raine** [purcell/sqlint#10]
A book on PostgreSQL contains the following example code where the backslash command is causing sqlint to fail. I'm not experienced enough in SQL to say if this error is appropriate or not but PostgreSQL runs it fine. 

```sql
BEGIN;


CREATE TABLE factbook (
  year int,
  date date,
  shares text,
  trades text,
  dollars text
);

\copy factbook FROM 'factbook.csv' WITH delimiter '\t' null ''

ALTER TABLE factbook
  ALTER shares
   TYPE bigint
  USING replace(shares, ',', '')::bigint,

  ALTER trades
   TYPE bigint
  USING replace(shares, ',', '')::bigint,

  ALTER dollars
   TYPE bigint
  USING substring(replace(dollars, ',', '') from 2)::numeric;

COMMIT;
```

```
12:1:ERROR syntax error at or near "\"
```

**Comment by purcell** [comment]
`\copy` and other commands beginning `\` are internal commands available inside `psql` but are not proper SQL commands. The behaviour here is therefore correct, in my view -- I wouldn't want to add a special case for the backslash commands, then, given that they couldn't be executed via a PostgreSQL client library.
