### ISSUE TITLE
macOS/Linux package for Nix Packages collection

### ISSUE THREAD

**Issue by ariutta** [purcell/sqlint#11]
Thanks for creating this tool -- it's useful!

I wrote a [macOS/Linux package](https://github.com/NixOS/nixpkgs/pull/41901) for it to add to the [Nix Packages collection](https://nixos.org/nixos/nix-pills/why-you-should-give-it-a-try.html). I listed myself as the maintainer, but since it's your library, I'm happy to hand it over to you. Just let me know. 

If you're interested, you can add yourself to the [maintainer list](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) and edit the files in [`pkgs/development/tools/sqlint`](https://github.com/NixOS/nixpkgs/pull/41901/files). ([Additional details](https://nixos.org/nixpkgs/manual/#sec-language-ruby) regarding Nix and Ruby.)

**Comment by ariutta** [comment]
I'm having some trouble handling the `libpg_query` dependency, as described [here](https://github.com/NixOS/nixpkgs/pull/41901#discussion_r195611215) Any ideas?

**Comment by ariutta** [comment]
The issue [was resolved](https://github.com/NixOS/nixpkgs/pull/41901#issuecomment-397784980) by @ryantm. Soon you'll be able to [install Nix](https://nixos.org/nix/manual/#chap-quick-start) and run
```
nix-env -iA nixos.sqlint
```
to install `sqlint` on macOS and Linux.

**Comment by purcell** [comment]
Oh nice, thanks for the heads-up!
