### ISSUE TITLE
Inconsistency between sqlint.gemspec and Gemfile.lock?

### ISSUE THREAD

**Issue by ariutta** [purcell/sqlint#12]
It appears these two files refer to different versions of pgquery (`0.13.5` vs. `1.0.0`):
https://github.com/purcell/sqlint/blob/master/sqlint.gemspec#L39
https://github.com/purcell/sqlint/blob/master/Gemfile.lock#L6

**Comment by purcell** [comment]
Thanks - fixed in 73889c9 / v0.1.8
