### ISSUE TITLE
Backticks are considered a syntax error

### ISSUE THREAD

**Issue by mikedfunk** [purcell/sqlint#19]
e.g.
```sql
SELECT * FROM `my_table`
```

**Comment by purcell** [comment]
You didn't say what database you're using, but backticks are not ANSI-compliant. I'm guessing you're using MySQL, in which case I imagine you could instead use the standard double-quotes.

**Comment by purcell** [comment]
(In MySQL you can apparently use `SET sql_mode = 'ANSI_QUOTES';` to get standards-compliant behaviour.)

**Comment by mikedfunk** [comment]
Sorry, yes, MySQL. I always thought backticks were preferred in order to avoid problems with reserved words, kind of like double-quoting variables in bash. I didn't realize it was not standards-compliant.

**Comment by devnix** [comment]
Could be a possibility of ignoring backticks as a syntax error if passing a specific parameter?
