### ISSUE TITLE
Cant support create db if not exists command

### ISSUE THREAD

**Issue by santhosh34** [purcell/sqlint#24]
CREATE DATABASE IF NOT EXISTS somedd;
Tool throwing ERROR syntax error at or near "NOT"

**Comment by purcell** [comment]
I think this is a side effect of #22, ie. we're waiting on an update in an upstream library in order to support PostgreSQL 12+ syntax like this.

**Comment by purcell** [comment]
So: closed at duplicate, but thanks for the report.
