### ISSUE TITLE
Where gets sqlint the SQL-keywords?

### ISSUE THREAD

**Issue by ReneFroger** [purcell/sqlint#4]
When I was typing in the SQL-buffer in pair with `sqlint`, I got an error from sqlint that the `USE`-keyword would not be a valid SQL-word, like

      USE database;

But it's really a normal SQL-statement, see also [this source](http://www.tutorialspoint.com/sql/sql-select-database.htm). 

So it led me to wondering where sqlint got the list of valid SQL-keywords?

**Comment by purcell** [comment]
I don't think that's an ANSI standard. As noted in the README, sqlint currently only explicitly supports the PostgreSQL syntax, which is a superset of ANSI SQL. In its current form, this tool effectively wraps a standalone version of the PostgreSQL query parser.
