### ISSUE TITLE
Feature request: support for mysql

### ISSUE THREAD

**Issue by mallt** [purcell/sqlint#8]
First of all thanks a lot for creating this linter! 

It would be great if there would be support for the mysql syntax as well. Is there any chance this could be added? Thanks!

**Comment by purcell** [comment]
Hi! We use the `pg_query` gem for this, which [embeds a copy](https://pganalyze.com/blog/parse-postgresql-queries-in-ruby.html) of PostgreSQL's query parser. I'm not aware that there's an equivalent for MySQL's dialect of SQL, but if such a thing exists or gets written, then we'd be able to integrate it. It's not something I'm going to actively pursue on my own time, though, sorry.

**Comment by mallt** [comment]
Ok, thank you for the clarification!
